# Importing Functions from Another Jupyter Notebook

There are several ways to import functions from `soccerpredict.ipynb`:

In [6]:
import numpy as np
%run liga_f.ipynb
import pandas as pd

# Read the Liga F all fixtures CSV file
pl_df = pd.read_csv('data/pl/premier_league_all_fixtures_2026-01-04.csv')
pl_df['home_score'] = pl_df['home_score'].fillna(0.0)
pl_df['away_score'] = pl_df['away_score'].fillna(0.0)

Original dataset shape: (960, 20)

Available seasons:
season
2022-2023    240
2023-2024    240
2024-2025    240
2025-2026    240
Name: count, dtype: int64

Filtered dataset for 2022-2023 season shape: (240, 20)
Number of matches: 240
Home Win Coefficients: [0.25 0.5  0.75 1.   1.25 1.5  1.75]
Away Win Coefficients: [0.25 0.5  0.75 1.   1.25 1.5  1.75]
Margin Coefficients: [0.  0.5 1. ]
Date Coefficients: [0.  0.5 1. ]
Rankings identical? False
False
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.00, Error=7.7460, Mean%Diff=0.1389
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Levante', 'Atlético Madrid', 'Madrid CFF', 'Real Sociedad', 'Valencia', 'Sporting Huelva', 'Sevilla', 'Tenerife', 'Levante Planas', 'Athletic Club', 'Real Betis', 'Villarreal', 'Alavés', 'Alhama']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Levante', 'Atlético Madrid', 'Madrid CFF', 'Tenerife', 'Sevilla', 'Real Sociedad', 'Valencia', 'Athletic Club', 'Levante Planas', 'Real Betis', 'Sporting Huelva', 'Villarreal', 'Alhama', 'Alavés']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.50, Date Coeff=0.00, Error=7.6158, Mean%Diff=0.1371
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Levante', 'Atlético Madrid', 'Madrid CFF', 'Real Sociedad', 'Valencia', 'Sevilla', 'Sporting Huelva', 'Athletic Club', 'Tenerife', 'Levante Planas', 'Real Betis', 'Alavés', 'Villarreal', 'Alhama']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Levante', 'Atlético Madrid', 'Madrid CFF', 'Tenerife', 'Sevilla', 'Real Sociedad', 'Valencia', 'Athletic Club', 'Levante Planas', 'Real Betis', 'Sporting Huelva', 'Villarreal', 'Alhama', 'Alavés']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=1.00, Date Coeff=0.00, Error=6.3246, Mean%Diff=0.1236
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Levante', 'Atlético Madrid', 'Madrid CFF', 'Real Sociedad', 'Valencia', 'Sevilla', 'Athletic Club', 'Tenerife', 'Sporting Huelva', 'Levante Planas', 'Real Betis', 'Alavés', 'Alhama', 'Villarreal']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Levante', 'Atlético Madrid', 'Madrid CFF', 'Tenerife', 'Sevilla', 'Real Sociedad', 'Valencia', 'Athletic Club', 'Levante Planas', 'Real Betis', 'Sporting Huelva', 'Villarreal', 'Alhama', 'Alavés']
--------------------------------------------------------------------------------

Colley Optimization Complete:
Best Home Win Coefficient: 0.25
Best Away Win Coefficient: 0.25
Best Margin Coefficient: 1.00
Best Date Coefficient: 0.00
Best Error: 6.3246
Best Mean Percentage Difference: 0.1236
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.00, Error=7.3485, Mean%Diff=0.1560
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Madrid CFF', 'Levante', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Athletic Club', 'Levante Planas', 'Valencia', 'Villarreal', 'Real Betis', 'Eibar', 'Granada', 'Sporting Huelva']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.50, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.00, Error=7.0711, Mean%Diff=0.1510
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Madrid CFF', 'Levante', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Levante Planas', 'Athletic Club', 'Valencia', 'Real Betis', 'Eibar', 'Villarreal', 'Granada', 'Sporting Huelva']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.75, Away Coeff=0.25, Margin Coeff=0.50, Date Coeff=0.00, Error=6.9282, Mean%Diff=0.1229
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Levante Planas', 'Athletic Club', 'Valencia', 'Real Betis', 'Eibar', 'Villarreal', 'Granada', 'Sporting Huelva']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.75, Away Coeff=0.50, Margin Coeff=0.00, Date Coeff=0.00, Error=6.7823, Mean%Diff=0.1223
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Levante Planas', 'Athletic Club', 'Valencia', 'Eibar', 'Real Betis', 'Villarreal', 'Granada', 'Sporting Huelva']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=1.00, Away Coeff=0.75, Margin Coeff=0.00, Date Coeff=0.50, Error=6.4807, Mean%Diff=0.1148
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Athletic Club', 'Levante Planas', 'Eibar', 'Villarreal', 'Valencia', 'Real Betis', 'Granada', 'Sporting Huelva']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=1.50, Away Coeff=0.50, Margin Coeff=0.00, Date Coeff=0.00, Error=6.3246, Mean%Diff=0.1298
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Madrid CFF', 'Levante', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Levante Planas', 'Athletic Club', 'Eibar', 'Real Betis', 'Valencia', 'Granada', 'Villarreal', 'Sporting Huelva']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------

Colley Optimization Complete:
Best Home Win Coefficient: 1.50
Best Away Win Coefficient: 0.50
Best Margin Coefficient: 0.00
Best Date Coefficient: 0.00
Best Error: 6.3246
Best Mean Percentage Difference: 0.1298
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.00, Error=8.6023, Mean%Diff=0.1925
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Real Sociedad', 'Atlético Madrid', 'Athletic Club', 'Granada', 'Tenerife', 'Levante Badalona', 'Eibar', 'Espanyol', 'Madrid CFF', 'Real Betis', 'Sevilla', 'Dep La Coruña', 'Levante', 'Valencia']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Athletic Club', 'Granada', 'Tenerife', 'Real Sociedad', 'Eibar', 'Sevilla', 'Madrid CFF', 'Espanyol', 'Levante', 'Lavante Badalona', 'Dep La Coruña', 'Valencia', 'Real Betis']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.50, Date Coeff=0.00, Error=7.8740, Mean%Diff=0.1669
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Real Sociedad', 'Athletic Club', 'Granada', 'Tenerife', 'Levante Badalona', 'Espanyol', 'Madrid CFF', 'Eibar', 'Sevilla', 'Real Betis', 'Dep La Coruña', 'Levante', 'Valencia']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Athletic Club', 'Granada', 'Tenerife', 'Real Sociedad', 'Eibar', 'Sevilla', 'Madrid CFF', 'Espanyol', 'Levante', 'Lavante Badalona', 'Dep La Coruña', 'Valencia', 'Real Betis']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=1.00, Date Coeff=0.00, Error=7.7460, Mean%Diff=0.1675
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Real Sociedad', 'Athletic Club', 'Granada', 'Tenerife', 'Levante Badalona', 'Madrid CFF', 'Espanyol', 'Eibar', 'Sevilla', 'Real Betis', 'Dep La Coruña', 'Levante', 'Valencia']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Athletic Club', 'Granada', 'Tenerife', 'Real Sociedad', 'Eibar', 'Sevilla', 'Madrid CFF', 'Espanyol', 'Levante', 'Lavante Badalona', 'Dep La Coruña', 'Valencia', 'Real Betis']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.50, Away Coeff=0.50, Margin Coeff=1.00, Date Coeff=0.00, Error=7.6158, Mean%Diff=0.1676
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Real Sociedad', 'Athletic Club', 'Granada', 'Tenerife', 'Levante Badalona', 'Madrid CFF', 'Espanyol', 'Sevilla', 'Eibar', 'Real Betis', 'Levante', 'Dep La Coruña', 'Valencia']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Athletic Club', 'Granada', 'Tenerife', 'Real Sociedad', 'Eibar', 'Sevilla', 'Madrid CFF', 'Espanyol', 'Levante', 'Lavante Badalona', 'Dep La Coruña', 'Valencia', 'Real Betis']
--------------------------------------------------------------------------------

Colley Optimization Complete:
Best Home Win Coefficient: 0.50
Best Away Win Coefficient: 0.50
Best Margin Coefficient: 1.00
Best Date Coefficient: 0.00
Best Error: 7.6158
Best Mean Percentage Difference: 0.1676

C:\Users\Naufal\AppData\Local\Temp\ipykernel_20836\2341830475.py:21: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(mode_at_min_mpd)
C:\Users\Naufal\AppData\Local\Temp\ipykernel_20836\2670775696.py:21: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(mode_at_min_mpd)

New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.00, Error=5.8310, Mean%Diff=0.0965
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Levante', 'Atlético Madrid', 'Madrid CFF', 'Real Sociedad', 'Sevilla', 'Athletic Club', 'Valencia', 'Tenerife', 'Levante Planas', 'Sporting Huelva', 'Real Betis', 'Alavés', 'Alhama', 'Villarreal']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Levante', 'Atlético Madrid', 'Madrid CFF', 'Tenerife', 'Sevilla', 'Real Sociedad', 'Valencia', 'Athletic Club', 'Levante Planas', 'Real Betis', 'Sporting Huelva', 'Villarreal', 'Alhama', 'Alavés']
--------------------------------------------------------------------------------

Massey Optimization Complete:
Best Home Win Coefficient: 0.25
Best Away Win Coefficient: 0.25
Best Margin Coefficient: 0.00
Best Date Coefficient: 0.00
Best Error: 5.8310
Best Mean Percentage Difference: 0.0965
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.00, Error=9.1652, Mean%Diff=0.1693
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Madrid CFF', 'Levante', 'Sevilla', 'Real Sociedad', 'Athletic Club', 'Tenerife', 'Levante Planas', 'Granada', 'Valencia', 'Villarreal', 'Sporting Huelva', 'Eibar', 'Real Betis']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.50, Error=8.1240, Mean%Diff=0.1308
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Sevilla', 'Real Sociedad', 'Athletic Club', 'Tenerife', 'Levante Planas', 'Granada', 'Villarreal', 'Valencia', 'Eibar', 'Real Betis', 'Sporting Huelva']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=1.25, Margin Coeff=0.00, Date Coeff=0.50, Error=7.8740, Mean%Diff=0.2267
predicted ranked teams:  ['Barcelona', 'Atlético Madrid', 'Levante', 'Real Madrid', 'Madrid CFF', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Athletic Club', 'Levante Planas', 'Valencia', 'Eibar', 'Villarreal', 'Granada', 'Sporting Huelva', 'Real Betis']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=1.25, Margin Coeff=0.50, Date Coeff=1.00, Error=7.7460, Mean%Diff=0.2458
predicted ranked teams:  ['Barcelona', 'Atlético Madrid', 'Levante', 'Real Madrid', 'Sevilla', 'Madrid CFF', 'Tenerife', 'Real Sociedad', 'Athletic Club', 'Levante Planas', 'Valencia', 'Eibar', 'Granada', 'Sporting Huelva', 'Real Betis', 'Villarreal']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=1.25, Margin Coeff=1.00, Date Coeff=1.00, Error=7.4833, Mean%Diff=0.2225
predicted ranked teams:  ['Barcelona', 'Atlético Madrid', 'Levante', 'Real Madrid', 'Madrid CFF', 'Sevilla', 'Tenerife', 'Real Sociedad', 'Athletic Club', 'Levante Planas', 'Eibar', 'Granada', 'Valencia', 'Sporting Huelva', 'Real Betis', 'Villarreal']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=1.50, Margin Coeff=1.00, Date Coeff=1.00, Error=7.4833, Mean%Diff=0.2123
predicted ranked teams:  ['Barcelona', 'Atlético Madrid', 'Levante', 'Real Madrid', 'Madrid CFF', 'Sevilla', 'Tenerife', 'Real Sociedad', 'Athletic Club', 'Levante Planas', 'Eibar', 'Valencia', 'Sporting Huelva', 'Granada', 'Real Betis', 'Villarreal']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=1.75, Margin Coeff=0.50, Date Coeff=1.00, Error=7.3485, Mean%Diff=0.2325
predicted ranked teams:  ['Barcelona', 'Atlético Madrid', 'Levante', 'Real Madrid', 'Sevilla', 'Madrid CFF', 'Tenerife', 'Real Sociedad', 'Athletic Club', 'Levante Planas', 'Eibar', 'Valencia', 'Sporting Huelva', 'Real Betis', 'Granada', 'Villarreal']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------

Massey Optimization Complete:
Best Home Win Coefficient: 0.25
Best Away Win Coefficient: 1.75
Best Margin Coefficient: 0.50
Best Date Coefficient: 1.00
Best Error: 7.3485
Best Mean Percentage Difference: 0.2325
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.00, Error=6.8557, Mean%Diff=0.1328
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Real Sociedad', 'Athletic Club', 'Tenerife', 'Granada', 'Eibar', 'Levante Badalona', 'Sevilla', 'Espanyol', 'Madrid CFF', 'Real Betis', 'Dep La Coruña', 'Levante', 'Valencia']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Athletic Club', 'Granada', 'Tenerife', 'Real Sociedad', 'Eibar', 'Sevilla', 'Madrid CFF', 'Espanyol', 'Levante', 'Lavante Badalona', 'Dep La Coruña', 'Valencia', 'Real Betis']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.50, Date Coeff=0.00, Error=6.4807, Mean%Diff=0.1393
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Real Sociedad', 'Athletic Club', 'Tenerife', 'Granada', 'Levante Badalona', 'Eibar', 'Sevilla', 'Madrid CFF', 'Espanyol', 'Real Betis', 'Levante', 'Dep La Coruña', 'Valencia']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Athletic Club', 'Granada', 'Tenerife', 'Real Sociedad', 'Eibar', 'Sevilla', 'Madrid CFF', 'Espanyol', 'Levante', 'Lavante Badalona', 'Dep La Coruña', 'Valencia', 'Real Betis']
--------------------------------------------------------------------------------

Massey Optimization Complete:
Best Home Win Coefficient: 0.25
Best Away Win Coefficient: 0.25
Best Margin Coefficient: 0.50
Best Date Coefficient: 0.00
Best Error: 6.4807
Best Mean Percentage Difference: 0.1393

C:\Users\Naufal\AppData\Local\Temp\ipykernel_20836\2341830475.py:21: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(mode_at_min_mpd)
C:\Users\Naufal\AppData\Local\Temp\ipykernel_20836\2001641750.py:21: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(mode_at_min_mpd)

In [7]:
truePremierLeague2024_2025 = [ "Liverpool", "Arsenal", "Manchester City", "Chelsea", "Newcastle Utd", "Aston Villa", "Nott'ham Forest", "Brighton", "Bournemouth", "Brentford", "Fulham", "Crystal Palace", "Everton", "West Ham",  "Manchester Utd", "Wolves", "Tottenham",  "Leicester City", "Ipswich Town", "Southampton"]

# Define the range for home win coefficients
home_win_coeffs = np.arange(0.25, 1.76, 0.25)

# Define the range for away win coefficients
away_win_coeffs = np.arange(0.25, 1.76, 0.25)

# Define the range for away win coefficients
margin_coeffs = np.arange(0.0, 1.01, 0.50)

# Define the range for date  coefficients
date_coeffs = np.arange(0, 1.01, 0.5)

print("Home Win Coefficients:", home_win_coeffs)
print("Away Win Coefficients:", away_win_coeffs)
print("Margin Coefficients:", margin_coeffs)
print("Date Coefficients:", date_coeffs)

train_pl_2024_2025 = pl_df[pl_df['date'] < '2024-11-01']

# Grid Search for Optimal Coefficients
best_error = float('inf')
best_mpd = float('inf')
best_home_coeff = None
best_away_coeff = None
best_margin_coeff = None


history = []   # will store one row per try

try_num = 0

for home_coeff in home_win_coeffs:
    for away_coeff in away_win_coeffs:
        for date_coeff in date_coeffs:
            for margin_coeff in margin_coeffs:
                # Run Colley with the current coefficients
                team_ratings, sorted_teams = Colley_weighted_optimized(train_pl_2024_2025, home_coeff, away_coeff, margin_coeff, date_coeff)

                # Validate the ranking
                err, mpd = validate_ranking(sorted_teams, truePremierLeague2024_2025)

                try_num += 1
                history.append({
                    "try": try_num,
                    "seasons" : '2024/25',
                    "home_coeff": home_coeff,
                    "away_coeff": away_coeff,
                    "margin_coeff": margin_coeff,
                    "date_coeff": date_coeff,
                    "Error": err,
                    "Mean%Diff": mpd
               })

               # Check if the current combination is better than the best found so far
                if (err < best_error) or (np.isclose(err, best_error) and mpd < best_mpd):
                    best_error = err
                    best_mpd = mpd
                    best_home_coeff = home_coeff
                    best_away_coeff = away_coeff
                    best_margin_coeff = margin_coeff
                    best_date_coeff = date_coeff
                    print(f"New best found: Home Coeff={best_home_coeff:.2f}, Away Coeff={best_away_coeff:.2f}, Margin Coeff={best_margin_coeff:.2f}, Date Coeff={best_date_coeff:.2f}, Error={best_error:.4f}, Mean%Diff={best_mpd:.4f}")
                    print("predicted ranked teams: ", sorted_teams)
                    print("actual ranked teams:    ", truePremierLeague2024_2025)
                    print("--------------------------------------------------------------------------------")


print("\nColley Optimization Complete:")
print(f"Best Home Win Coefficient: {best_home_coeff:.2f}")
print(f"Best Away Win Coefficient: {best_away_coeff:.2f}")
print(f"Best Margin Coefficient: {best_margin_coeff:.2f}")
print(f"Best Date Coefficient: {best_date_coeff:.2f}")
print(f"Best Error: {best_error:.4f}")
print(f"Best Mean Percentage Difference: {best_mpd:.4f}")

Home Win Coefficients: [0.25 0.5  0.75 1.   1.25 1.5  1.75]
Away Win Coefficients: [0.25 0.5  0.75 1.   1.25 1.5  1.75]
Margin Coefficients: [0.  0.5 1. ]
Date Coefficients: [0.  0.5 1. ]
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.00, Error=10.8628, Mean%Diff=0.1921
predicted ranked teams:  ['Liverpool', 'Manchester City', 'Arsenal', 'Chelsea', 'Aston Villa', "Nott'ham Forest", 'Brighton', 'Bournemouth', 'Newcastle Utd', 'Tottenham', 'Brentford', 'Fulham', 'West Ham', 'Manchester Utd', 'Everton', 'Leicester City', 'Crystal Palace', 'Ipswich Town', 'Wolves', 'Southampton']
actual ranked teams:     ['Liverpool', 'Arsenal', 'Manchester City', 'Chelsea', 'Newcastle Utd', 'Aston Villa', "Nott'ham Forest", 'Brighton', 'Bournemouth', 'Brentford', 'Fulham', 'Crystal Palace', 'Everton', 'West Ham', 'Manchester Utd', 'Wolves', 'Tottenham', 'Leicester City', 'Ipswich Town', 'Southampton']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.50, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.00, Error=10.7703, Mean%Diff=0.2024
predicted ranked teams:  ['Liverpool', 'Manchester City', 'Arsenal', 'Chelsea', 'Aston Villa', "Nott'ham Forest", 'Brighton', 'Bournemouth', 'Newcastle Utd', 'West Ham', 'Fulham', 'Tottenham', 'Brentford', 'Manchester Utd', 'Everton', 'Leicester City', 'Crystal Palace', 'Ipswich Town', 'Wolves', 'Southampton']
actual ranked teams:     ['Liverpool', 'Arsenal', 'Manchester City', 'Chelsea', 'Newcastle Utd', 'Aston Villa', "Nott'ham Forest", 'Brighton', 'Bournemouth', 'Brentford', 'Fulham', 'Crystal Palace', 'Everton', 'West Ham', 'Manchester Utd', 'Wolves', 'Tottenham', 'Leicester City', 'Ipswich Town', 'Southampton']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.50, Away Coeff=0.50, Margin Coeff=0.00, Date Coeff=0.00, Error=10.6771, Mean%Diff=0.2599
predicted ranked teams:  ['Manchester City', 'Liverpool', 'Arsenal', 'Chelsea', 'Aston Villa', 'Brighton', "Nott'ham Forest", 'Bournemouth', 'Newcastle Utd', 'Fulham', 'Tottenham', 'Brentford', 'West Ham', 'Manchester Utd', 'Everton', 'Leicester City', 'Crystal Palace', 'Ipswich Town', 'Wolves', 'Southampton']
actual ranked teams:     ['Liverpool', 'Arsenal', 'Manchester City', 'Chelsea', 'Newcastle Utd', 'Aston Villa', "Nott'ham Forest", 'Brighton', 'Bournemouth', 'Brentford', 'Fulham', 'Crystal Palace', 'Everton', 'West Ham', 'Manchester Utd', 'Wolves', 'Tottenham', 'Leicester City', 'Ipswich Town', 'Southampton']
--------------------------------------------------------------------------------

Colley Optimization Complete:
Best Home Win Coefficient: 0.50
Best Away Win Coefficient: 0.50
Best Margin Coefficient: 0.00
Best Date Coefficient: 0.00
Best Error: 10.6771
Best Mean Percentage Difference: 0.2599

In [8]:
hist_df = pd.DataFrame(history)
hist_df.head(5)

,try,seasons,home_coeff,away_coeff,margin_coeff,date_coeff,Error,Mean%Diff
0,1,2024/25,0.25,0.25,0.0,0.0,10.862780,0.192075
1,2,2024/25,0.25,0.25,0.5,0.0,13.038405,0.209480
2,3,2024/25,0.25,0.25,1.0,0.0,13.711309,0.206171
3,4,2024/25,0.25,0.25,0.0,0.5,11.489125,0.200848
4,5,2024/25,0.25,0.25,0.5,0.5,13.928388,0.276289

In [9]:
from scipy import stats

vars_to_mode = ["home_coeff", "away_coeff", "margin_coeff", "date_coeff"]

def mode_at_min_mpd(df):
    min_mpd = df["Mean%Diff"].min()
    best_rows = df[df["Mean%Diff"] == min_mpd]
    
    mode_values = {}
    for col in vars_to_mode:
        m = best_rows[col].mode()
        # if multiple modes, take the first (deterministic)
        mode_values[col] = float(m.iloc[0])
    
    return pd.Series(mode_values)

# per-season
season_result = (
    hist_df
    .groupby("seasons")
    .apply(mode_at_min_mpd)
)

# ALL seasons
all_result = mode_at_min_mpd(hist_df).to_frame(name="ALL").T

# same orientation as before
final_table = pd.concat([season_result, all_result]).T

final_table

C:\Users\Naufal\AppData\Local\Temp\ipykernel_20836\2508061481.py:21: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(mode_at_min_mpd)

              2024/25   ALL
home_coeff       0.25  0.25
away_coeff       0.25  0.25
margin_coeff     0.00  0.00
date_coeff       0.00  0.00

In [10]:
import altair as alt

hist_df = pd.DataFrame(history)

# best try per season (min Error, tie-break min Mean%Diff)
best_df = (hist_df.sort_values(["seasons", "Error", "Mean%Diff"])
           .groupby("seasons", as_index=False)
           .first()[["seasons", "home_coeff"]])

charts = []
for season in hist_df['seasons'].unique():
    season_df = hist_df[hist_df['seasons'] == season]
    season_best = best_df[best_df['seasons'] == season]
    
    base = alt.Chart(season_df).encode(
        x=alt.X("home_coeff:Q", title="home_coeff")
    )
    
    error_line = base.mark_boxplot().encode(
        y=alt.Y("Error:Q", scale=alt.Scale(zero=False), title="Error")
    )
    
    mpd_line = base.mark_boxplot().encode(
        y=alt.Y("Mean%Diff:Q", scale=alt.Scale(zero=False), title="Mean % Difference")
    )
    
    rules = alt.Chart(season_best).mark_rule(strokeDash=[6,4], color='red').encode(
        x=alt.X("home_coeff:Q", scale=alt.Scale(zero=False))
    )
    
    season_chart = alt.vconcat(
        (error_line + rules).properties(width=300, height=200, title=f"Season {season} - Error"),
        (mpd_line + rules).properties(width=300, height=200, title=f"Season {season} - Mean % Diff")
    )
    
    charts.append(season_chart)

chart = alt.hconcat(*charts)
chart

alt.HConcatChart(...)