In [35]:
library(broom)
library(tidyverse)

In [36]:
dat_c <- read.csv("resultsColley.csv")
dat_m <-read.csv("resultsMassey.csv")
print(head(dat_c))

  try seasons home_coeff away_coeff margin_coeff date_coeff    Error Mean.Diff
1   1 2022/23       0.75       1.25          0.0        0.0 8.717798 0.2273244
2   2 2022/23       0.75       1.25          0.5        0.0 8.485281 0.1749435
3   3 2022/23       0.75       1.25          1.0        0.0 7.745967 0.1593185
4   4 2022/23       0.75       1.25          1.5        0.0 7.348469 0.1429720
5   5 2022/23       0.75       1.25          0.0        0.5 8.602325 0.1752411
6   6 2022/23       0.75       1.25          0.5        0.5 7.874008 0.1596161

In [37]:
reg_c <- lm(Error ~ home_coeff + away_coeff + margin_coeff + date_coeff, data = dat_c)
reg_m <- lm(Error ~ home_coeff + away_coeff + margin_coeff + date_coeff, data = dat_m)

In [38]:
tidy(reg_c)
tidy(reg_m)

  term         estimate   std.error  statistic p.value
1 (Intercept)   8.7213499 0.21786670 40.030670 1.283410e-146
2 home_coeff    0.6531007 0.14716468  4.437890  1.157737e-05
3 away_coeff   -0.4093431 0.14716468 -2.781531  5.649937e-03
4 margin_coeff -0.4268278 0.05373694 -7.942911  1.768152e-14
5 date_coeff    0.2865693 0.05373694  5.332817  1.571020e-07

  term         estimate   std.error  statistic p.value
1 (Intercept)   9.0281154 0.24052762 37.534631 2.575357e-137
2 home_coeff   -0.3418420 0.16247169 -2.104009  3.596179e-02
3 away_coeff    0.2372101 0.16247169  1.460009  1.450229e-01
4 margin_coeff -0.1819509 0.05932627 -3.066953  2.300024e-03
5 date_coeff   -0.2641950 0.05932627 -4.453254  1.081303e-05

In [39]:
library(car)

vif(reg_c)
vif(reg_m)

  home_coeff   away_coeff margin_coeff   date_coeff
           1            1            1            1

  home_coeff   away_coeff margin_coeff   date_coeff
           1            1            1            1

In [40]:
install.packages("car")

Warning message:
"package 'car' is in use and will not be installed"

In [41]:
# LOWEST IN COLLEY

q <- 0.01  # 10%

err_cut <- quantile(dat_c$Error, q)
mpd_cut <- quantile(dat_c$Mean.Diff, q)

selected <- dat_c[
  dat_c$Error <= err_cut |
  dat_c$Mean.Diff <= mpd_cut,
]

selected

    try seasons home_coeff away_coeff margin_coeff date_coeff Error
4     4 2022/23 0.75       1.25       1.5          0.0        7.348469
8     8 2022/23 0.75       1.25       1.5          0.5        7.348469
16   16 2022/23 0.75       1.25       1.5          1.5        7.874008
19   19 2022/23 0.75       1.00       1.0          0.0        6.928203
20   20 2022/23 0.75       1.00       1.5          0.0        7.348469
32   32 2022/23 0.75       1.00       1.5          1.5        7.874008
36   36 2022/23 0.75       0.75       1.5          0.0        6.928203
240  96 2023/24 1.00       0.75       1.5          1.5        8.366600
280 136 2023/24 1.25       0.75       1.5          0.5        8.485281
288 144 2023/24 1.25       0.75       1.5          1.5        8.366600
    Mean.Diff
4   0.1429720
8   0.1429720
16  0.1418273
19  0.1443917
20  0.1429720
32  0.1418273
36  0.1443917
240 0.1415094
280 0.1404143
288 0.1415094

In [42]:
coef_avg <- colMeans(
  selected[, c("home_coeff", "away_coeff", "margin_coeff", "date_coeff")]
)

coef_avg

  home_coeff   away_coeff margin_coeff   date_coeff
       0.875        0.975        1.450        0.700