In [1]:
import numpy as np
%run liga_f.ipynb
import pandas as pd

# Read the Liga F all fixtures CSV file
wsl_df = pd.read_csv('data/wsl/wsl_all_fixtures_2025-10-30.csv')
wsl_df['home_score'] = wsl_df['home_score'].fillna(0.0)
wsl_df['away_score'] = wsl_df['away_score'].fillna(0.0)

Original dataset shape: (960, 20)

Available seasons:
season
2022-2023    240
2023-2024    240
2024-2025    240
2025-2026    240
Name: count, dtype: int64

Filtered dataset for 2022-2023 season shape: (240, 20)
Number of matches: 240
Home Win Coefficients: [0.25 0.5  0.75 1.   1.25 1.5  1.75]
Away Win Coefficients: [0.25 0.5  0.75 1.   1.25 1.5  1.75]
Margin Coefficients: [0.  0.5 1. ]
Date Coefficients: [0.  0.5 1. ]
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.00, Error=7.7460, Mean%Diff=0.1389
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Levante', 'Atlético Madrid', 'Madrid CFF', 'Real Sociedad', 'Valencia', 'Sporting Huelva', 'Sevilla', 'Tenerife', 'Levante Planas', 'Athletic Club', 'Real Betis', 'Villarreal', 'Alavés', 'Alhama']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Levante', 'Atlético Madrid', 'Madrid CFF', 'Tenerife', 'Sevilla', 'Real Sociedad', 'Valencia', 'Athletic Club', 'Levante Planas', 'Real Betis', 'Sporting Huelva', 'Villarreal', 'Alhama', 'Alavés']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.50, Date Coeff=0.00, Error=7.6158, Mean%Diff=0.1371
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Levante', 'Atlético Madrid', 'Madrid CFF', 'Real Sociedad', 'Valencia', 'Sevilla', 'Sporting Huelva', 'Athletic Club', 'Tenerife', 'Levante Planas', 'Real Betis', 'Alavés', 'Villarreal', 'Alhama']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Levante', 'Atlético Madrid', 'Madrid CFF', 'Tenerife', 'Sevilla', 'Real Sociedad', 'Valencia', 'Athletic Club', 'Levante Planas', 'Real Betis', 'Sporting Huelva', 'Villarreal', 'Alhama', 'Alavés']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=1.00, Date Coeff=0.00, Error=6.3246, Mean%Diff=0.1236
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Levante', 'Atlético Madrid', 'Madrid CFF', 'Real Sociedad', 'Valencia', 'Sevilla', 'Athletic Club', 'Tenerife', 'Sporting Huelva', 'Levante Planas', 'Real Betis', 'Alavés', 'Alhama', 'Villarreal']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Levante', 'Atlético Madrid', 'Madrid CFF', 'Tenerife', 'Sevilla', 'Real Sociedad', 'Valencia', 'Athletic Club', 'Levante Planas', 'Real Betis', 'Sporting Huelva', 'Villarreal', 'Alhama', 'Alavés']
--------------------------------------------------------------------------------

Colley Optimization Complete:
Best Home Win Coefficient: 0.25
Best Away Win Coefficient: 0.25
Best Margin Coefficient: 1.00
Best Date Coefficient: 0.00
Best Error: 6.3246
Best Mean Percentage Difference: 0.1236
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.00, Error=7.3485, Mean%Diff=0.1560
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Madrid CFF', 'Levante', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Athletic Club', 'Levante Planas', 'Valencia', 'Villarreal', 'Real Betis', 'Eibar', 'Granada', 'Sporting Huelva']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.50, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.00, Error=7.0711, Mean%Diff=0.1510
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Madrid CFF', 'Levante', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Levante Planas', 'Athletic Club', 'Valencia', 'Real Betis', 'Eibar', 'Villarreal', 'Granada', 'Sporting Huelva']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.75, Away Coeff=0.25, Margin Coeff=0.50, Date Coeff=0.00, Error=6.9282, Mean%Diff=0.1229
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Levante Planas', 'Athletic Club', 'Valencia', 'Real Betis', 'Eibar', 'Villarreal', 'Granada', 'Sporting Huelva']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.75, Away Coeff=0.50, Margin Coeff=0.00, Date Coeff=0.00, Error=6.7823, Mean%Diff=0.1223
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Levante Planas', 'Athletic Club', 'Valencia', 'Eibar', 'Real Betis', 'Villarreal', 'Granada', 'Sporting Huelva']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=1.00, Away Coeff=0.75, Margin Coeff=0.00, Date Coeff=0.50, Error=6.4807, Mean%Diff=0.1148
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Athletic Club', 'Levante Planas', 'Eibar', 'Villarreal', 'Valencia', 'Real Betis', 'Granada', 'Sporting Huelva']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=1.50, Away Coeff=0.50, Margin Coeff=0.00, Date Coeff=0.00, Error=6.3246, Mean%Diff=0.1298
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Madrid CFF', 'Levante', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Levante Planas', 'Athletic Club', 'Eibar', 'Real Betis', 'Valencia', 'Granada', 'Villarreal', 'Sporting Huelva']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------

Colley Optimization Complete:
Best Home Win Coefficient: 1.50
Best Away Win Coefficient: 0.50
Best Margin Coefficient: 0.00
Best Date Coefficient: 0.00
Best Error: 6.3246
Best Mean Percentage Difference: 0.1298
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.00, Error=8.6023, Mean%Diff=0.1925
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Real Sociedad', 'Atlético Madrid', 'Athletic Club', 'Granada', 'Tenerife', 'Levante Badalona', 'Eibar', 'Espanyol', 'Madrid CFF', 'Real Betis', 'Sevilla', 'Dep La Coruña', 'Levante', 'Valencia']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Athletic Club', 'Granada', 'Tenerife', 'Real Sociedad', 'Eibar', 'Sevilla', 'Madrid CFF', 'Espanyol', 'Levante', 'Lavante Badalona', 'Dep La Coruña', 'Valencia', 'Real Betis']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.50, Date Coeff=0.00, Error=7.8740, Mean%Diff=0.1669
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Real Sociedad', 'Athletic Club', 'Granada', 'Tenerife', 'Levante Badalona', 'Espanyol', 'Madrid CFF', 'Eibar', 'Sevilla', 'Real Betis', 'Dep La Coruña', 'Levante', 'Valencia']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Athletic Club', 'Granada', 'Tenerife', 'Real Sociedad', 'Eibar', 'Sevilla', 'Madrid CFF', 'Espanyol', 'Levante', 'Lavante Badalona', 'Dep La Coruña', 'Valencia', 'Real Betis']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=1.00, Date Coeff=0.00, Error=7.7460, Mean%Diff=0.1675
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Real Sociedad', 'Athletic Club', 'Granada', 'Tenerife', 'Levante Badalona', 'Madrid CFF', 'Espanyol', 'Eibar', 'Sevilla', 'Real Betis', 'Dep La Coruña', 'Levante', 'Valencia']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Athletic Club', 'Granada', 'Tenerife', 'Real Sociedad', 'Eibar', 'Sevilla', 'Madrid CFF', 'Espanyol', 'Levante', 'Lavante Badalona', 'Dep La Coruña', 'Valencia', 'Real Betis']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.50, Away Coeff=0.50, Margin Coeff=1.00, Date Coeff=0.00, Error=7.6158, Mean%Diff=0.1676
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Real Sociedad', 'Athletic Club', 'Granada', 'Tenerife', 'Levante Badalona', 'Madrid CFF', 'Espanyol', 'Sevilla', 'Eibar', 'Real Betis', 'Levante', 'Dep La Coruña', 'Valencia']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Athletic Club', 'Granada', 'Tenerife', 'Real Sociedad', 'Eibar', 'Sevilla', 'Madrid CFF', 'Espanyol', 'Levante', 'Lavante Badalona', 'Dep La Coruña', 'Valencia', 'Real Betis']
--------------------------------------------------------------------------------

Colley Optimization Complete:
Best Home Win Coefficient: 0.50
Best Away Win Coefficient: 0.50
Best Margin Coefficient: 1.00
Best Date Coefficient: 0.00
Best Error: 7.6158
Best Mean Percentage Difference: 0.1676

C:\Users\Naufal\AppData\Local\Temp\ipykernel_15680\2341830475.py:21: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(mode_at_min_mpd)
C:\Users\Naufal\AppData\Local\Temp\ipykernel_15680\2670775696.py:21: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(mode_at_min_mpd)

New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.00, Error=5.8310, Mean%Diff=0.0965
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Levante', 'Atlético Madrid', 'Madrid CFF', 'Real Sociedad', 'Sevilla', 'Athletic Club', 'Valencia', 'Tenerife', 'Levante Planas', 'Sporting Huelva', 'Real Betis', 'Alavés', 'Alhama', 'Villarreal']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Levante', 'Atlético Madrid', 'Madrid CFF', 'Tenerife', 'Sevilla', 'Real Sociedad', 'Valencia', 'Athletic Club', 'Levante Planas', 'Real Betis', 'Sporting Huelva', 'Villarreal', 'Alhama', 'Alavés']
--------------------------------------------------------------------------------

Massey Optimization Complete:
Best Home Win Coefficient: 0.25
Best Away Win Coefficient: 0.25
Best Margin Coefficient: 0.00
Best Date Coefficient: 0.00
Best Error: 5.8310
Best Mean Percentage Difference: 0.0965
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.00, Error=9.1652, Mean%Diff=0.1693
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Madrid CFF', 'Levante', 'Sevilla', 'Real Sociedad', 'Athletic Club', 'Tenerife', 'Levante Planas', 'Granada', 'Valencia', 'Villarreal', 'Sporting Huelva', 'Eibar', 'Real Betis']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.50, Error=8.1240, Mean%Diff=0.1308
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Sevilla', 'Real Sociedad', 'Athletic Club', 'Tenerife', 'Levante Planas', 'Granada', 'Villarreal', 'Valencia', 'Eibar', 'Real Betis', 'Sporting Huelva']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=1.25, Margin Coeff=0.00, Date Coeff=0.50, Error=7.8740, Mean%Diff=0.2267
predicted ranked teams:  ['Barcelona', 'Atlético Madrid', 'Levante', 'Real Madrid', 'Madrid CFF', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Athletic Club', 'Levante Planas', 'Valencia', 'Eibar', 'Villarreal', 'Granada', 'Sporting Huelva', 'Real Betis']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=1.25, Margin Coeff=0.50, Date Coeff=1.00, Error=7.7460, Mean%Diff=0.2458
predicted ranked teams:  ['Barcelona', 'Atlético Madrid', 'Levante', 'Real Madrid', 'Sevilla', 'Madrid CFF', 'Tenerife', 'Real Sociedad', 'Athletic Club', 'Levante Planas', 'Valencia', 'Eibar', 'Granada', 'Sporting Huelva', 'Real Betis', 'Villarreal']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=1.25, Margin Coeff=1.00, Date Coeff=1.00, Error=7.4833, Mean%Diff=0.2225
predicted ranked teams:  ['Barcelona', 'Atlético Madrid', 'Levante', 'Real Madrid', 'Madrid CFF', 'Sevilla', 'Tenerife', 'Real Sociedad', 'Athletic Club', 'Levante Planas', 'Eibar', 'Granada', 'Valencia', 'Sporting Huelva', 'Real Betis', 'Villarreal']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=1.50, Margin Coeff=1.00, Date Coeff=1.00, Error=7.4833, Mean%Diff=0.2123
predicted ranked teams:  ['Barcelona', 'Atlético Madrid', 'Levante', 'Real Madrid', 'Madrid CFF', 'Sevilla', 'Tenerife', 'Real Sociedad', 'Athletic Club', 'Levante Planas', 'Eibar', 'Valencia', 'Sporting Huelva', 'Granada', 'Real Betis', 'Villarreal']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=1.75, Margin Coeff=0.50, Date Coeff=1.00, Error=7.3485, Mean%Diff=0.2325
predicted ranked teams:  ['Barcelona', 'Atlético Madrid', 'Levante', 'Real Madrid', 'Sevilla', 'Madrid CFF', 'Tenerife', 'Real Sociedad', 'Athletic Club', 'Levante Planas', 'Eibar', 'Valencia', 'Sporting Huelva', 'Real Betis', 'Granada', 'Villarreal']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Levante', 'Madrid CFF', 'Athletic Club', 'Sevilla', 'Real Sociedad', 'Tenerife', 'Eibar', 'Real Betis', 'Valencia', 'Levante Planas', 'Granada', 'Villarreal', 'Sporting Huelva']
--------------------------------------------------------------------------------

Massey Optimization Complete:
Best Home Win Coefficient: 0.25
Best Away Win Coefficient: 1.75
Best Margin Coefficient: 0.50
Best Date Coefficient: 1.00
Best Error: 7.3485
Best Mean Percentage Difference: 0.2325
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.00, Error=6.8557, Mean%Diff=0.1328
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Real Sociedad', 'Athletic Club', 'Tenerife', 'Granada', 'Eibar', 'Levante Badalona', 'Sevilla', 'Espanyol', 'Madrid CFF', 'Real Betis', 'Dep La Coruña', 'Levante', 'Valencia']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Athletic Club', 'Granada', 'Tenerife', 'Real Sociedad', 'Eibar', 'Sevilla', 'Madrid CFF', 'Espanyol', 'Levante', 'Lavante Badalona', 'Dep La Coruña', 'Valencia', 'Real Betis']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.50, Date Coeff=0.00, Error=6.4807, Mean%Diff=0.1393
predicted ranked teams:  ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Real Sociedad', 'Athletic Club', 'Tenerife', 'Granada', 'Levante Badalona', 'Eibar', 'Sevilla', 'Madrid CFF', 'Espanyol', 'Real Betis', 'Levante', 'Dep La Coruña', 'Valencia']
actual ranked teams:     ['Barcelona', 'Real Madrid', 'Atlético Madrid', 'Athletic Club', 'Granada', 'Tenerife', 'Real Sociedad', 'Eibar', 'Sevilla', 'Madrid CFF', 'Espanyol', 'Levante', 'Lavante Badalona', 'Dep La Coruña', 'Valencia', 'Real Betis']
--------------------------------------------------------------------------------

Massey Optimization Complete:
Best Home Win Coefficient: 0.25
Best Away Win Coefficient: 0.25
Best Margin Coefficient: 0.50
Best Date Coefficient: 0.00
Best Error: 6.4807
Best Mean Percentage Difference: 0.1393

C:\Users\Naufal\AppData\Local\Temp\ipykernel_15680\2341830475.py:21: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(mode_at_min_mpd)
C:\Users\Naufal\AppData\Local\Temp\ipykernel_15680\2001641750.py:21: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(mode_at_min_mpd)

In [2]:
trueWSL2024_2025 = trueWSL2024_2025 = [
    "Chelsea",        # Champions (1st) — unbeaten season 🏆
    "Arsenal",        # 2nd — UEFA Women’s Champions League spot
    "Manchester Utd",  # 3rd — European qualification
    "Manchester City",    # 4th
    "Brighton",  # 5th
    "Aston Villa",    # 6th
    "Liverpool",      # 7th
    "Everton",        # 8th
    "West Ham",# 9th
    "Leicester City", # 10th
    "Tottenham", # 11th
    "Crystal Palace"
]


# Define the range for home win coefficients
home_win_coeffs = np.arange(0.25, 1.76, 0.25)

# Define the range for away win coefficients
away_win_coeffs = np.arange(0.25, 1.76, 0.25)

# Define the range for away win coefficients
margin_coeffs = np.arange(0.0, 1.01, 0.50)

# Define the range for date  coefficients
date_coeffs = np.arange(0, 1.01, 0.5)

print("Home Win Coefficients:", home_win_coeffs)
print("Away Win Coefficients:", away_win_coeffs)
print("Margin Coefficients:", margin_coeffs)
print("Date Coefficients:", date_coeffs)

train_wsl_2024_2025 = wsl_df[(wsl_df['season'] == '2024-2025') & (wsl_df['gameweek'] <= 11)]

# Grid Search for Optimal Coefficients
best_error = float('inf')
best_mpd = float('inf')
best_home_coeff = None
best_away_coeff = None
best_margin_coeff = None


history = []   # will store one row per try

try_num = 0

for home_coeff in home_win_coeffs:
    for away_coeff in away_win_coeffs:
        for date_coeff in date_coeffs:
            for margin_coeff in margin_coeffs:
                # Run Colley with the current coefficients
                team_ratings, sorted_teams = Colley_weighted_optimized(train_wsl_2024_2025, home_coeff, away_coeff, margin_coeff, date_coeff)

                # Validate the ranking
                err, mpd = validate_ranking(sorted_teams, trueWSL2024_2025)

                try_num += 1
                history.append({
                    "try": try_num,
                    "seasons" : '2024/25',
                    "home_coeff": home_coeff,
                    "away_coeff": away_coeff,
                    "margin_coeff": margin_coeff,
                    "date_coeff": date_coeff,
                    "Error": err,
                    "Mean%Diff": mpd
               })

               # Check if the current combination is better than the best found so far
                if (err < best_error) or (np.isclose(err, best_error) and mpd < best_mpd):
                    best_error = err
                    best_mpd = mpd
                    best_home_coeff = home_coeff
                    best_away_coeff = away_coeff
                    best_margin_coeff = margin_coeff
                    best_date_coeff = date_coeff
                    print(f"New best found: Home Coeff={best_home_coeff:.2f}, Away Coeff={best_away_coeff:.2f}, Margin Coeff={best_margin_coeff:.2f}, Date Coeff={best_date_coeff:.2f}, Error={best_error:.4f}, Mean%Diff={best_mpd:.4f}")
                    print("predicted ranked teams: ", sorted_teams)
                    print("actual ranked teams:    ", trueWSL2024_2025)
                    print("--------------------------------------------------------------------------------")


print("\nColley Optimization Complete:")
print(f"Best Home Win Coefficient: {best_home_coeff:.2f}")
print(f"Best Away Win Coefficient: {best_away_coeff:.2f}")
print(f"Best Margin Coefficient: {best_margin_coeff:.2f}")
print(f"Best Date Coefficient: {best_date_coeff:.2f}")
print(f"Best Error: {best_error:.4f}")
print(f"Best Mean Percentage Difference: {best_mpd:.4f}")

Home Win Coefficients: [0.25 0.5  0.75 1.   1.25 1.5  1.75]
Away Win Coefficients: [0.25 0.5  0.75 1.   1.25 1.5  1.75]
Margin Coefficients: [0.  0.5 1. ]
Date Coefficients: [0.  0.5 1. ]
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.00, Date Coeff=0.00, Error=5.8310, Mean%Diff=0.0941
predicted ranked teams:  ['Chelsea', 'Arsenal', 'Manchester Utd', 'Manchester City', 'Brighton', 'Tottenham', 'Aston Villa', 'Everton', 'Liverpool', 'Leicester City', 'West Ham', 'Crystal Palace']
actual ranked teams:     ['Chelsea', 'Arsenal', 'Manchester Utd', 'Manchester City', 'Brighton', 'Aston Villa', 'Liverpool', 'Everton', 'West Ham', 'Leicester City', 'Tottenham', 'Crystal Palace']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=0.50, Date Coeff=0.00, Error=5.6569, Mean%Diff=0.0937
predicted ranked teams:  ['Chelsea', 'Arsenal', 'Manchester Utd', 'Manchester City', 'Brighton', 'Tottenham', 'Liverpool', 'Aston Villa', 'Everton', 'West Ham', 'Leicester City', 'Crystal Palace']
actual ranked teams:     ['Chelsea', 'Arsenal', 'Manchester Utd', 'Manchester City', 'Brighton', 'Aston Villa', 'Liverpool', 'Everton', 'West Ham', 'Leicester City', 'Tottenham', 'Crystal Palace']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=1.00, Date Coeff=0.00, Error=5.4772, Mean%Diff=0.0917
predicted ranked teams:  ['Chelsea', 'Arsenal', 'Manchester Utd', 'Manchester City', 'Brighton', 'Tottenham', 'Aston Villa', 'Liverpool', 'Everton', 'West Ham', 'Leicester City', 'Crystal Palace']
actual ranked teams:     ['Chelsea', 'Arsenal', 'Manchester Utd', 'Manchester City', 'Brighton', 'Aston Villa', 'Liverpool', 'Everton', 'West Ham', 'Leicester City', 'Tottenham', 'Crystal Palace']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=0.25, Margin Coeff=1.00, Date Coeff=0.50, Error=4.6904, Mean%Diff=0.0717
predicted ranked teams:  ['Chelsea', 'Arsenal', 'Manchester Utd', 'Manchester City', 'Brighton', 'Aston Villa', 'Tottenham', 'Everton', 'Liverpool', 'West Ham', 'Leicester City', 'Crystal Palace']
actual ranked teams:     ['Chelsea', 'Arsenal', 'Manchester Utd', 'Manchester City', 'Brighton', 'Aston Villa', 'Liverpool', 'Everton', 'West Ham', 'Leicester City', 'Tottenham', 'Crystal Palace']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=0.50, Margin Coeff=1.00, Date Coeff=0.50, Error=3.4641, Mean%Diff=0.0507
predicted ranked teams:  ['Chelsea', 'Arsenal', 'Manchester Utd', 'Manchester City', 'Brighton', 'Aston Villa', 'Liverpool', 'Tottenham', 'Everton', 'West Ham', 'Leicester City', 'Crystal Palace']
actual ranked teams:     ['Chelsea', 'Arsenal', 'Manchester Utd', 'Manchester City', 'Brighton', 'Aston Villa', 'Liverpool', 'Everton', 'West Ham', 'Leicester City', 'Tottenham', 'Crystal Palace']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=0.75, Margin Coeff=1.00, Date Coeff=0.50, Error=3.1623, Mean%Diff=0.1280
predicted ranked teams:  ['Chelsea', 'Manchester Utd', 'Arsenal', 'Manchester City', 'Brighton', 'Liverpool', 'Aston Villa', 'Everton', 'Tottenham', 'West Ham', 'Leicester City', 'Crystal Palace']
actual ranked teams:     ['Chelsea', 'Arsenal', 'Manchester Utd', 'Manchester City', 'Brighton', 'Aston Villa', 'Liverpool', 'Everton', 'West Ham', 'Leicester City', 'Tottenham', 'Crystal Palace']
--------------------------------------------------------------------------------
New best found: Home Coeff=0.25, Away Coeff=0.75, Margin Coeff=1.00, Date Coeff=1.00, Error=2.4495, Mean%Diff=0.0327
predicted ranked teams:  ['Chelsea', 'Arsenal', 'Manchester Utd', 'Manchester City', 'Brighton', 'Aston Villa', 'Liverpool', 'Everton', 'Tottenham', 'West Ham', 'Leicester City', 'Crystal Palace']
actual ranked teams:     ['Chelsea', 'Arsenal', 'Manchester Utd', 'Manchester City', 'Brighton', 'Aston Villa', 'Liverpool', 'Everton', 'West Ham', 'Leicester City', 'Tottenham', 'Crystal Palace']
--------------------------------------------------------------------------------

Colley Optimization Complete:
Best Home Win Coefficient: 0.25
Best Away Win Coefficient: 0.75
Best Margin Coefficient: 1.00
Best Date Coefficient: 1.00
Best Error: 2.4495
Best Mean Percentage Difference: 0.0327

In [3]:
train_wsl_2024_2025

,season,gameweek,date,day_of_week,start_time,home_team,away_team,home_score,away_score,score,home_xg,away_xg,venue,attendance,referee,status,result,home_team_url,away_team_url,match_report_url
132,2024-2025,1.0,2024-09-20,Fri,19:00 (11:00),Chelsea,Aston Villa,1.0,0.0,1–0,1.1,0.9,Cherry Red Records Fans' Stadium,4337.0,Kirsty Dowle,completed,home_win,https://fbref.com/en/squads/a6a4e67d/2024-2025...,https://fbref.com/en/squads/53157aa8/2024-2025...,https://fbref.com/en/matches/460a420c/Chelsea-...
133,2024-2025,1.0,2024-09-21,Sat,12:00 (04:00),Manchester Utd,West Ham,3.0,0.0,3–0,1.2,0.9,Old Trafford,8761.0,Cheryl Foster,completed,home_win,https://fbref.com/en/squads/0bbd83f6/2024-2025...,https://fbref.com/en/squads/52d65cea/2024-2025...,https://fbref.com/en/matches/247d25af/Manchest...
134,2024-2025,1.0,2024-09-21,Sat,12:30 (04:30),Brighton,Everton,4.0,0.0,4–0,2.1,0.5,Broadfield Stadium,2125.0,Lauren Impey,completed,home_win,https://fbref.com/en/squads/fa2752bc/2024-2025...,https://fbref.com/en/squads/c4989550/2024-2025...,https://fbref.com/en/matches/86c90fdf/Brighton...
135,2024-2025,1.0,2024-09-22,Sun,12:30 (04:30),Arsenal,Manchester City,2.0,2.0,2–2,2.2,1.4,Emirates Stadium,41818.0,Abigail Byrne,completed,draw,https://fbref.com/en/squads/411b1108/2024-2025...,https://fbref.com/en/squads/9ce68f8a/2024-2025...,https://fbref.com/en/matches/9232742b/Arsenal-...
136,2024-2025,1.0,2024-09-22,Sun,14:00 (06:00),Tottenham,Crystal Palace,4.0,0.0,4–0,4.1,0.3,The BetWright Stadium,1778.0,Amy Fearn,completed,home_win,https://fbref.com/en/squads/e8e4577c/2024-2025...,https://fbref.com/en/squads/78ba1bd4/Crystal-P...,https://fbref.com/en/matches/4d436423/Tottenha...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,2024-2025,11.0,2025-01-18,Sat,17:30 (09:30),Everton,Aston Villa,1.0,1.0,1–1,0.4,1.1,Walton Hall Park,973.0,Stacey Fullicks,completed,draw,https://fbref.com/en/squads/c4989550/2024-2025...,https://fbref.com/en/squads/53157aa8/2024-2025...,https://fbref.com/en/matches/9e365585/Everton-...
194,2024-2025,11.0,2025-01-19,Sun,12:30 (04:30),Tottenham,Leicester City,1.0,0.0,1–0,0.0,1.3,The BetWright Stadium,1314.0,Stacey Pearson,completed,home_win,https://fbref.com/en/squads/e8e4577c/2024-2025...,https://fbref.com/en/squads/23bce84e/2024-2025...,https://fbref.com/en/matches/91ce25ab/Tottenha...
195,2024-2025,11.0,2025-01-19,Sun,14:00 (06:00),Arsenal,Crystal Palace,5.0,0.0,5–0,3.2,0.9,Mangata Pay UK Stadium,3576.0,Phoebe Cross,completed,home_win,https://fbref.com/en/squads/411b1108/2024-2025...,https://fbref.com/en/squads/78ba1bd4/Crystal-P...,https://fbref.com/en/matches/0475ac77/Arsenal-...
196,2024-2025,11.0,2025-01-19,Sun,15:00 (07:00),West Ham,Chelsea,0.0,5.0,0–5,0.4,2.3,Chigwell Construction Stadium,2461.0,Amy Fearn,completed,away_win,https://fbref.com/en/squads/52d65cea/2024-2025...,https://fbref.com/en/squads/a6a4e67d/2024-2025...,https://fbref.com/en/matches/10a0825a/West-Ham...
197,2024-2025,11.0,2025-01-19,Sun,18:45 (10:45),Manchester City,Manchester Utd,2.0,4.0,2–4,1.8,2.7,Etihad Stadium,22497.0,Lisa Benn,completed,away_win,https://fbref.com/en/squads/9ce68f8a/2024-2025...,https://fbref.com/en/squads/0bbd83f6/2024-2025...,https://fbref.com/en/matches/2ed728f6/Manchest...

In [4]:
hist_df = pd.DataFrame(history)
hist_df.head(5)

,try,seasons,home_coeff,away_coeff,margin_coeff,date_coeff,Error,Mean%Diff
0,1,2024/25,0.25,0.25,0.0,0.0,5.830952,0.094096
1,2,2024/25,0.25,0.25,0.5,0.0,5.656854,0.093666
2,3,2024/25,0.25,0.25,1.0,0.0,5.477226,0.091682
3,4,2024/25,0.25,0.25,0.0,0.5,5.830952,0.094096
4,5,2024/25,0.25,0.25,0.5,0.5,5.656854,0.093170

In [5]:
from scipy import stats

vars_to_mode = ["home_coeff", "away_coeff", "margin_coeff", "date_coeff"]

def mode_at_min_mpd(df):
    min_mpd = df["Mean%Diff"].min()
    best_rows = df[df["Mean%Diff"] == min_mpd]
    
    mode_values = {}
    for col in vars_to_mode:
        m = best_rows[col].mode()
        # if multiple modes, take the first (deterministic)
        mode_values[col] = float(m.iloc[0])
    
    return pd.Series(mode_values)

# per-season
season_result = (
    hist_df
    .groupby("seasons")
    .apply(mode_at_min_mpd)
)

# ALL seasons
all_result = mode_at_min_mpd(hist_df).to_frame(name="ALL").T

# same orientation as before
final_table = pd.concat([season_result, all_result]).T

final_table

C:\Users\Naufal\AppData\Local\Temp\ipykernel_15680\2508061481.py:21: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(mode_at_min_mpd)

              2024/25   ALL
home_coeff       0.25  0.25
away_coeff       0.75  0.75
margin_coeff     1.00  1.00
date_coeff       1.00  1.00